name: Run tests
on:
  pull_request:
    branches:
      - master

permissions:
  checks: write

jobs:

  run-maven-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Get Chrome version
        run: chrome --version

      - name: Run tests with Maven
        run: ./mvnw clean test

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: maven-test-results
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit
          fail-on-error: true